update rosetta
ElrondNetwork/observing-squad pull request #20
Opened 2021-09-08 14:18 UTC by miiu96

2021-11-18 09:41 UTC, bogdan-rosianu requested changes

2021-11-18 09:41 UTC, bogdan-rosianu commented on rosetta-devnet/.env
> +STACK_FOLDER_NAME=MyObservingSquadDevnet
empty line

2021-11-19 08:52 UTC, AdoAdoAdo approved these changes

2021-11-19 08:54 UTC, bogdan-rosianu approved these changes

2021-11-19 12:14 UTC, merged

2021-11-19 12:14 UTC, AdoAdoAdo approved these changes